ACFT_flagged	709DF6
ACFT_ignored	505050
ACFT_linked   FBC166
ACFT_unlinked	707070
AD_holding_lines	darkred
AD_parking_position	cccc00
AD_runway	18192F
AD_tarmac	18192F
AD_taxiway_lines	867E23
AD_viewpoint	white
FPL_closed	808000
FPL_filed	cccccc
FPL_filed_outdated	666666
FPL_open	00cc44
FPL_open_noETA	cccc00
FPL_open_overdue	ff4444
GND_route_apron	8844aa
GND_route_taxiway	cc5050
LDG_guide_ILS	3080d0
LDG_guide_noILS	d03080
RDF_line	yellow
RWY_incursion	ff0000
RWY_reserved	ccff00
XPDR_call	ff0000
XPDR_identification	2525ff
assignment_OK	cccccc
assignment_bad	ff4444
loose_strip_bay_background	1a1a00
measuring_tool	white
nav_RNAV	666666
nav_aid	5555ff
nav_airfield	2F3A53
nav_fix	009000
point_indicator	yellow
radar_background 050805
radar_circle	151515
radar_range_limit	olive
radar_tag_line	404040
route_followed	00cc44
route_overridden	aaaa00
selection_indicator	white
separation_ring_OK	707070
separation_ring_bad	ee3300
separation_ring_warning	887700
strip_linked_OK	1a3a1a
strip_linked_alert	3a1010
strip_linked_warning	3a2800
strip_unlinked	303030
strip_unlinked_identified	1a1a4a