Please note that $icao is controlled. Contact ATC if any intentions.
Go ahead.
Stand by.
QNH $qnh
qnhg|QNH $qnhg
Runways in use: $runways
Wind $wind
Squawk $sq
Number $nseq, traffic ahead
delsid|Cleared to $dest via $wpsid departure, initial FL 100, squawk $sq, expect runway $rwydep.
delvect|Cleared to $dest via vectors, initial FL 100, squawk $sq, expect runway $rwydep.
rbc|Read back correct, report ready for start-up.
Push-back and start-up approved, report ready to taxi.
luw|Runway $rwy, line up and wait
cto|Wind $wind, runway $rwy, cleared for take-off
Intercept LOC, cleared ILS, report runway in sight.
ctl|Wind $wind, runway $rwy, cleared to land
lost|You are identified on a $qdm bearing to the airport, $dist out.
?cp|Did you copy?
?alt|Say altitude
?pos|Say position
?ias|Say indicated air speed
?mach|Say Mach number
?int|Say intentions
?app|Say type of approach requested
?acft|Say type of aircraft
??radio|Are you able radio, FGCom $frq?
??xpdr|Are you able transponder?
??vor|Are you able VOR navigation?
??taxi|Are you able to taxi?
ATC service now closing at $icao. Fly safe, good bye.
